# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: leaf_it_to_me
    build: .
    command: gunicorn -b 0.0.0.0:5000 leaf_it_to_me.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/leaf_it_to_me.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./leaf_it_to_me:/code/leaf_it_to_me
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: leaf_it_to_me
    command: "celery worker -A leaf_it_to_me.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
