from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))


class Plant(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    AlternateName = db.Column(db.String(80), nullable=True, default=None)
    Edible = db.Column(db.String(80), nullable=True, default=None)
    EdibleParts = db.Column(db.String(80), nullable=True, default=None)
    EdibleUses = db.Column(db.String(80), nullable=True, default=None)
    Family = db.Column(db.String(80))
    Growth = db.Column(db.String(10), nullable=True, default=None)
    Height = db.Column(db.String(80))
    Habitat = db.Column(db.String(80), nullable=True, default=None)
    Layer = db.Column(db.String(80), nullable=True, default=None)
    Leaves = db.Column(db.String(80), nullable=True, default=None)
    LifeCycle = db.Column(db.String(80), nullable=True, default=None)
    LightRequirement = db.Column(db.String(80))
    Name = db.Column(db.String(80))
    GermanName = db.Column(db.String(80), nullable=True, default=None)
    PlantsForAFuture = db.Column(db.String(80))
    ScientificName = db.Column(db.String(80))
    SoilType = db.Column(db.String(80))
    SoilPh = db.Column(db.String(80), nullable=True, default=None)
    UsdaHardinessZone = db.Column(db.String(80))
    Utility = db.Column(db.String(80), nullable=True, default=None)
    WaterRequirement = db.Column(db.String(80))
    Wikipedia = db.Column(db.String(80))
    WhenToPlantOutdoors = db.Column(db.String(80), nullable=True, default=None)
    WhenToPlantIndoors = db.Column(db.String(80), nullable=True, default=None)
    WhenToPlantTransplant = db.Column(db.String(80), nullable=True, default=None)
    PropagationTransplanting = db.Column(db.String(80), nullable=True, default=None)
    DaysToMaturity = db.Column(db.String(80), nullable=True, default=None)
    GerminationTime = db.Column(db.String(80), nullable=True, default=None)
    PropagationDirectSowing = db.Column(db.String(80), nullable=True, default=None)
    Medicinal = db.Column(db.String(80), nullable=True, default=None)
    RootDepth = db.Column(db.String(80), nullable=True, default=None)
    RootType = db.Column(db.String(80), nullable=True, default=None)
    Diseases = db.Column(db.String(80), nullable=True, default=None)
    Pests = db.Column(db.String(80), nullable=True, default=None)
    NativeTo = db.Column(db.String(80), nullable=True, default=None)
    Spread = db.Column(db.String(80), nullable=True, default=None)
    DroughtResistant = db.Column(db.String(80), nullable=True, default=None)
    MedicinalParts = db.Column(db.String(80), nullable=True, default=None)
    WhenToPlantDivision = db.Column(db.String(80), nullable=True, default=None)
    DroughtTolerant = db.Column(db.String(80), nullable=True, default=None)
    WhenToHarvest = db.Column(db.String(80), nullable=True, default=None)
    SeedPlantingDepth = db.Column(db.String(80), nullable=True, default=None)
    Varieties = db.Column(db.String(80), nullable=True, default=None)
    DaysToHarvest = db.Column(db.String(80), nullable=True, default=None)
    Pollination = db.Column(db.String(80), nullable=True, default=None)
    Cultivars = db.Column(db.String(80), nullable=True, default=None)
    ColdStratificationTemperature = db.Column(db.String(80), nullable=True, default=None)
    ColdStratificationTime= db.Column(db.String(80), nullable=True, default=None)
    WhenToPlantCuttings = db.Column(db.String(80), nullable=True, default=None)
    InvasiveIn = db.Column(db.String(80), nullable=True, default=None)
    Hortipedia = db.Column(db.String(80), nullable=True, default=None)
    PropagationCuttings = db.Column(db.String(80), nullable=True, default=None)
    UsefulTropicalPlants = db.Column(db.String(80), nullable=True, default=None)
    YearsToBear = db.Column(db.String(80), nullable=True, default=None)
    Genus = db.Column(db.String(80), nullable=True, default=None)
    SeedDepth = db.Column(db.String(80), nullable=True, default=None)
    Warning = db.Column(db.String(80), nullable=True, default=None)
    Spacing = db.Column(db.String(80), nullable=True, default=None)
    PropagationMethod = db.Column(db.String(80), nullable=True, default=None)
    GerminationTemperature = db.Column(db.String(80), nullable=True, default=None)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship("Note")
    plants = db.relationship("Plant")
